<?php
$subCategories = array(
    'business',
    'entertainment',
    'health',
    'science',
    'sports',
    'technology'
);



$newsSources = array(
    $questionable = array(
        'nationalenq'  => 'http://www.nationalenquirer.com',
        'townhall'     => 'http://townhall.com',
        'dailymail-uk' => 'http://www.dailymail.co.uk',
        'usnews'       => 'http://www.usnews.com',
        'frisky'       => 'http://www.thefrisky.com'
    ),

    $conspiracy = array(
        'cbn' => 'http://cbn.com'
    ),

    $entertainment = array(
        'allure'            => 'http://www.allure.com',
        'animenews'         => 'http://www.animenewsnetwork.com',
        'bet'               => 'http://www.bet.com',
        'betterhome'        => 'https://www.bhg.com/',
        'billboard'         => 'http://www.billboard.com',
        'celebuzz'          => 'http://celebuzz.com',
        'cosmo'             => 'http://www.cosmopolitan.com',
        'ebony'             => 'http://www.ebony.com',
        'etonline'          => 'http://www.etonline.com',
        'elle'              => 'http://www.elle.com',
        'eonline'           => 'http://www.eonline.com',
        'escapistmagazine'  => 'http://www.escapistmagazine.com',
        'eurogamer'         => 'http://www.eurogamer.net',
        'ew'                => 'http://www.ew.com',
        'glam'              => 'http://glam.com',
        'glamour'           => 'http://www.glamour.com',
        'hollywood'         => 'http://www.hollywood.com',
        'hollywoodreporter' => 'http://www.hollywoodreporter.com',
        'maxim'             => 'http://www.maxim.com',
        'mtv'               => 'http://www.mtv.com',
        'peoplestylewatch'  => 'http://www.peoplestylewatch.com',
        'perezhilton'       => 'http://perezhilton.com',
        'teenvogue'         => 'http://www.teenvogue.com',
        'vogue'             => 'http://www.vogue.co.uk',
        'style'             => 'http://www.style.com',
        'theboot'           => 'http://theboot.com',
        'tmz'               => 'http://www.tmz.com',
        'usmagazine'        => 'http://www.usmagazine.com',
        'variety'           => 'http://www.variety.com',
        'vhone'             => 'http://www.vh1.com',
        'whosdatedwho'      => 'http://www.whosdatedwho.com',
    ),

    $sports = array(
        'autoblog'      => 'http://autoblog.com',
        'autochannel'   => 'http://www.theautochannel.com',
        'automobilemag' => 'http://www.automobilemag.com',
        'autonews'      => 'http://www.autonews.com',
        'bodybuilding'  => 'http://www.bodybuilding.com',
        'carconnection' => 'http://thecarconnection.com',
        'cbsports'      => 'http://www.cbssports.com',
        'deadspin'      => 'http://deadspin.com',
        'espn'          => 'http://espn.com',
        'espnfone'      => 'http://espnf1.com',
        'foxsports'     => 'http://foxsports.com',
        'mlb'           => 'http://mlb.com',
        'mlsoccer'      => 'http://www.mlssoccer.com',
        'nascar'        => 'http://www.nascar.com',
        'nba'           => 'http://www.nba.com',
        'nbcsports'     => 'http://nbcsports.nbc.com',
        'nfl'           => 'http://www.nfl.com',
        'rivals'        => 'http://www.n.rivals.com',
        'sbnation'      => 'http://www.sbnation.com',
        'sportingnews'  => 'http://sportingnews.com',
        'tennis'        => 'http://www.tennis.com',
        'topgear'       => 'http://www.topgear.com',
        'topspeed'      => 'http://www.topspeed.com',
    ),
    
    $science = array(
        'nasa'             => 'http://www.nasa.gov',
        'popsci'           => 'http://www.popsci.com',
        'natgeo'           => 'http://nationalgeographic.com',
        'discovermagazine' => 'http://discovermagazine.com',
        'phys'             => 'http://phys.org',
        'sciencedaily'     => 'http://www.sciencedaily.com',
        'sciencemag'       => 'http://sciencemag.org',
        'space'            => 'http://www.space.com',
        'newscientist'     => 'http://www.newscientist.com',
        'scinews'          => 'http://www.sci-news.com',
        'futurism'         => 'https://futurism.com',
    ),
    $tech = array(
        'pcgamer'           => 'http://www.pcgamer.com',
        'eweek'             => 'http://www.eweek.com',
        'techreview'        => 'http://www.technologyreview.com',
        'extremetech'       => 'http://www.extremetech.com',
        'gamespot'          => 'http://www.gamespot.com',
        'engadget'          => 'http://www.engadget.com',
        'techreport'        => 'http://techreport.com',
        'techspot'          => 'http://www.techspot.com',
        'tech'              => 'http://tech.mit.edu',
        'pcworld'           => 'http://www.pcworld.com',
        'zdnet'             => 'http://zdnet.com',
        'techworld'         => 'http://techworld.com.au',
        'techmeme'          => 'http://www.techmeme.com',
        'digitaltrends'     => 'http://www.digitaltrends.com',
        'techradar'         => 'http://www.techradar.com',
        'techrunch'         => 'http://techcrunch.com',
        'techdigest'        => 'http://techdigest.tv',
        'ycombinator'       => 'http://news.ycombinator.com',
        'infoworld'         => 'http://www.infoworld.com',
        'cnet'              => 'http://cnet.com',
        'pcmag'             => 'http://pcmag.com',
        'ign'               => 'http://www.ign.com',
        'searchenginewatch' => 'http://blog.searchenginewatch.com',
        'solarnovis'        => 'http://www.solarnovus.com',
        'venturebeat'       => 'http://venturebeat.com',
        'apple'             => 'http://www.apple.com',
        'macworld'          => 'http://www.macworld.com',
        'microsoft'         => 'http://www.microsoft.com',
        'popularmechanics'  => 'http://www.popularmechanics.com',

    ),

    $rightwing = array(
        'nypost'             => 'http://www.nypost.com',
        'heritage'           => 'http://heritage.org',
        'foxbiz'             => 'http://www.foxbusiness.com',
        'washingtontimes'    => 'http://washingtontimes.com',
        'washingtonexaminer' => 'http://washingtonexaminer.com',
        'hotair'             => 'http://hotair.com',
        'forbes'             => 'http://www.forbes.com',
        'thestreet'          => 'http://www.thestreet.com',
        'realclearpolitics'  => 'http://www.realclearpolitics.com',
        'thedailywire'       => 'http://dailywire.com',
        'redstate'           => 'http://www.redstate.com',
        'breitbart'          => 'http://breitbart.com',
        'foxnews'            => 'http://foxnews.com',
        'citizen'            => 'http://thecitizen.com',
        'wsj'                => 'http://wsj.com',
    ),

    $leftwing               = array(
        'abcnews'        => 'http://abcnews.com',
        'aljazeera'      => 'http://www.aljazeera.com',
        'atlantic'       => 'http://theatlantic.com',
        'bbc'            => 'http://www.bbc.co.uk',
        'bbcamerica'     => 'http://www.bbcamerica.com',
        'berkely'        => 'http://blogs.berkeley.edu',
        'bizinsider'     => 'http://www.businessinsider.com',
        'bleachereport'  => 'http://bleacherreport.com',
        'bng'            => 'http://www.bhg.com',
        'buzzfeed'       => 'http://www.buzzfeed.com',
        'cbc'            => 'http://www.cbc.ca',
        'cbsnews'        => 'http://www.cbsnews.com',
        'cnn'            => 'http://cnn.com',
        'cnbc'           => 'http://cnbc.com',
        'crimson'        => 'http://thecrimson.com',
        'dailybeast'     => 'http://thedailybeast.com',
        'drudgereport'   => 'http://drudgereport.com',
        'fastco'         => 'http://www.fastcompany.com',
        'guardian'       => 'http://www.guardiannews.com',
        'gq'             => 'http://www.gq.com',
        'hbr'            => 'http://hbr.org',
        'huff'           => 'http://www.huffingtonpost.com',
        'independent'    => 'http://independent.co.uk',
        'latimes'        => 'http://www.latimes.com',
        'lifehacker'     => 'http://lifehacker.com',
        'kotaku'         => 'http://kotaku.com',
        'marketwatch'    => 'http://www.marketwatch.com',
        'mashable'       => 'http://mashable.com',
        'medium'         => 'http://medium.com',
        'miamiherald'    => 'http://www.miamiherald.com',
        'msn'            => 'http://msn.com',
        'newrepublic'    => 'http://www.newrepublic.com',
        'nbcnews'        => 'http://www.nbcnews.com',
        'newsroom'       => 'http://newsroom.fb.com',
        'npr'            => 'http://npr.org',
        'nydailynews'    => 'http://www.nydailynews.com',
        'nymag'          => 'http://nymag.com',
        'nyt'            => 'http://nytimes.com',
        'pbs'            => 'http://www.pbs.org',
        'people'         => 'http://www.people.com',
        'politico'       => 'http://www.politico.com',
        'politifact'     => 'http://www.politifact.com',
        'polygon'        => 'http://www.polygon.com',
        'religionews'    => 'http://www.religionnews.com',
        'rollingstone'   => 'http://www.rollingstone.com',
        'seattlepi'      => 'http://seattlepi.com',
        'seattletimes'   => 'http://seattletimes.com',
        'sfgate'         => 'http://www.sfgate.com',
        'sky'            => 'http://news.sky.com',
        'slashdot'       => 'http://slashdot.org',
        'slate'          => 'http://www.slate.com',
        'stltoday'       => 'http://www.stltoday.com',
        'suntimes'       => 'http://www.suntimes.com',
        'ted'            => 'http://ted.com',
        'thinkprogress'  => 'http://thinkprogress.org',
        'time'           => 'http://time.com',
        'today'          => 'http://www.today.com',
        'usatoday'       => 'http://usatoday.com',
        'vanityfair'     => 'http://www.vanityfair.com',
        'verge'          => 'http://www.theverge.com',
        'vice'           => 'http://www.vice.com',
        'washingtonian'  => 'http://washingtonian.com',
        'washingtonpost' => 'http://washingtonpost.com',
        'wired'          => 'http://www.wired.com',
        'yahoo'          => 'http://yahoo.com',
    ),

    $centrist               = array(
        "abcchicago"            => "http://abc7chicago.com",
        "abcsevenny"            => "http://abc7ny.com",
        "abctwelve"             => "http://abc12.com",
        "abscbn"                => "http://news.abs-cbn.com",
        "actionjax"             => "http://actionnewsjax.com",
        "adfontes"              => "http//adfontesmedia.co",
        "adweek"                => "http://adweek.com",
        "africacheck"           => "http://africacheck.org",
        "agdaily"               => "http://agdaily.com",
        "airforcetimes"         => "http://airforcetimes.com",
        "alabamapolitical"      => "http://alreporter.com",
        "alabamatoday"          => "http://altoday.com",
        "albanydemherald"       => "http://democratherald.com",
        "allafrica"             => "http://allafrica.com",
        "amarilloglobe"         => "http://amarillo.com",
        "americanheritage"      => "http://americanheritage.com",
        "americanmilitary"      => "http://americanmilitarynews.com",
        "americanpress"         => "http://americanpressinstitute.com",
        "andersonindependent"   => "http://independentmail.com",
        "ap"                    => "http://apnews.com",
        "arizonacapitoltimes"   => "http://azcapitoltimes.com",
        "armytimes"             => "http://armytimes.com",
        "arstechnica"           => "http://arstechnica.com",
        "asiatimes"             => "http://atimes.com",
        "atlasobscura"          => "http://atlasobscura.com",
        "ballotpedia"           => "http://ballotpedia.org",
        "cspan"                 => "http://www.c-span.org",
        "foreignpolicy"         => "http://foreignpolicy.com",
        "fourteenforty"         => "http://join1440.com",
        "ninenews"              => "http://9news.com",
        "securingdemocracy"     => "http://securingdemocracy.gmfus.org",
        "sixeighty"             => "http://680news.com",
        "sunsentinel"           => "http://www.sun-sentinel.com",
        "thehill"               => "http://thehill.com",
        "twelvenews"            => "http://12news.com",
        "twentyfoursevenwallst" => "http://247wallst.com",
        "twentyfourur"          => "http://24ur.com",
        "thirtyeightnorth"      => "http://www.38.north.org",
        "tenten"                => "http://1010wins.radio.com",
    ),
);

print_r($newsSources[0]);
